# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: airCenseLora.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='airCenseLora.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12\x61irCenseLora.proto\"y\n\rairCenseProto\x12\x0b\n\x03NO2\x18\x01 \x02(\x02\x12\n\n\x02\x43O\x18\x02 \x02(\x02\x12\x13\n\x0btemperature\x18\x03 \x02(\x02\x12\x10\n\x08humidity\x18\x04 \x02(\x02\x12\x0b\n\x03\x43O2\x18\x05 \x02(\x05\x12\r\n\x05PM2_5\x18\x06 \x02(\x02\x12\x0c\n\x04PM10\x18\x07 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_AIRCENSEPROTO = _descriptor.Descriptor(
  name='airCenseProto',
  full_name='airCenseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='NO2', full_name='airCenseProto.NO2', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CO', full_name='airCenseProto.CO', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='airCenseProto.temperature', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='airCenseProto.humidity', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CO2', full_name='airCenseProto.CO2', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PM2_5', full_name='airCenseProto.PM2_5', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PM10', full_name='airCenseProto.PM10', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['airCenseProto'] = _AIRCENSEPROTO

airCenseProto = _reflection.GeneratedProtocolMessageType('airCenseProto', (_message.Message,), dict(
  DESCRIPTOR = _AIRCENSEPROTO,
  __module__ = 'airCenseLora_pb2'
  # @@protoc_insertion_point(class_scope:airCenseProto)
  ))
_sym_db.RegisterMessage(airCenseProto)


# @@protoc_insertion_point(module_scope)
