/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue Jul  3 12:58:21 2018. */

#include "airCenseLora.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t airCenseProto_fields[8] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, airCenseProto, NO2, NO2, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, airCenseProto, CO, NO2, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, airCenseProto, temperature, CO, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, airCenseProto, humidity, temperature, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, airCenseProto, CO2, humidity, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, airCenseProto, PM2_5, CO2, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, airCenseProto, PM10, PM2_5, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
